// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHnQcW4oGP0L8Eoizb97JEZAfl0u3CzG8',
    appId: '1:39126517990:web:6d0c141f2709f868261327',
    messagingSenderId: '39126517990',
    projectId: 'quizzzy-12',
    authDomain: 'quizzzy-12.firebaseapp.com',
    storageBucket: 'quizzzy-12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7YKFhnyzWw6cwmHqczIgI2-dBE_WW-Lg',
    appId: '1:39126517990:android:19e16b9c5a24e58c261327',
    messagingSenderId: '39126517990',
    projectId: 'quizzzy-12',
    storageBucket: 'quizzzy-12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt4DZ3C9P6fbeoWXGRvOw6-XpzTYrdDNs',
    appId: '1:39126517990:ios:dc1552c0302192e0261327',
    messagingSenderId: '39126517990',
    projectId: 'quizzzy-12',
    storageBucket: 'quizzzy-12.appspot.com',
    iosClientId: '39126517990-sdhtvm2npqcvfuvvt46uge4v1kp06qmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt4DZ3C9P6fbeoWXGRvOw6-XpzTYrdDNs',
    appId: '1:39126517990:ios:dc1552c0302192e0261327',
    messagingSenderId: '39126517990',
    projectId: 'quizzzy-12',
    storageBucket: 'quizzzy-12.appspot.com',
    iosClientId: '39126517990-sdhtvm2npqcvfuvvt46uge4v1kp06qmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
